<#
  ラベル印刷エージェントを Windows ログオン時に自動起動するタスクとして登録する

  使い方（自分のユーザーで。管理者権限は不要）:
    powershell -ExecutionPolicy Bypass -File scripts\print-agent\install-task.ps1
  WSL から呼ぶなら:
    /mnt/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe -NoProfile -ExecutionPolicy Bypass -File "$(wslpath -w scripts/print-agent/install-task.ps1)"

  やること:
    1. タスクスケジューラに "WelfareLabelPrintAgent" を登録（ログオン時＋10分ごと・非表示・失敗時3回再試行）
       🔴 バッテリ条件を外す（2026-09-11）。ノートPC なので電源を抜いた瞬間に Windows がタスクを止め、
          次のログオンまで戻らなかった（9/10 09:41 に黙って止まり、ラベルが 10 件溜まった）。
          10分ごとのトリガーは「死んでいたら上げ直す」ため。動いている間は IgnoreNew で無視される。
    2. そのまま今すぐ起動する
  外し方:
    Unregister-ScheduledTask -TaskName WelfareLabelPrintAgent -Confirm:$false

  タスクの中身は launch.ps1 を -File で呼ぶだけ（引用符の入れ子を避けるため）。

  🔴 起動は wscript.exe（launch.vbs・ウィンドウ 0＝非表示・終わるまで待つ）経由にする（2026-09-11）。
     powershell.exe を直接タスクの action にすると、この PC では **窓が見える**（Windows Terminal が既定のため
     -WindowStyle Hidden が効かない）。10分ごとの上げ直しトリガーのたびに窓が出て、
     閉じるとエージェントが道連れで死ぬ（17:10 の実行が STATUS_CONTROL_C_EXIT で終わっていた）。
     他の10本のタスク（wscript + .bat）は同じ形で窓が出ていない。launch.vbs はこのスクリプトが生成する。
#>
param(
  [string]$Distro   = "Ubuntu",
  [string]$TaskName = "WelfareLabelPrintAgent"
)

$ErrorActionPreference = "Stop"

$launcher = Join-Path $PSScriptRoot "launch.ps1"
if (-not (Test-Path $launcher)) { throw "launch.ps1 が見つかりません: $launcher" }

# 非表示で起動し、エージェントが生きている間は待つ（True）。待つのでタスクは「実行中」のままになり、
# 10分ごとのトリガーは IgnoreNew で無視される。エージェントが死ぬと wscript も終わり、次のトリガーで上がる。
$vbsPath = Join-Path $PSScriptRoot "launch.vbs"
$vbs = @(
  "' Generated by install-task.ps1 - do not edit. Starts launch.ps1 hidden and waits while the agent runs.",
  ('CreateObject("Wscript.Shell").Run "powershell.exe -NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -File ""{0}"" -Distro {1}", 0, True' -f $launcher, $Distro)
)
Set-Content -LiteralPath $vbsPath -Value $vbs -Encoding Ascii

$action = New-ScheduledTaskAction -Execute "wscript.exe" -Argument "`"$vbsPath`""

$triggers = @(
  (New-ScheduledTaskTrigger -AtLogOn -User $env:USERNAME),
  # 死んでいたら10分以内に上げ直す（動いている間は MultipleInstances=IgnoreNew で何もしない）
  (New-ScheduledTaskTrigger -Once -At (Get-Date).Date -RepetitionInterval (New-TimeSpan -Minutes 10) -RepetitionDuration (New-TimeSpan -Days 3650))
)
$settings = New-ScheduledTaskSettingsSet `
  -ExecutionTimeLimit ([TimeSpan]::Zero) `
  -RestartCount 3 -RestartInterval (New-TimeSpan -Minutes 1) `
  -MultipleInstances IgnoreNew `
  -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries `
  -StartWhenAvailable -Hidden

Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $triggers -Settings $settings -Force | Out-Null
Start-ScheduledTask -TaskName $TaskName

Write-Host "OK: $TaskName を登録して起動しました"
Write-Host "   ログ:  wsl.exe -d $Distro -- tail -f ~/print-agent.log"
Write-Host "   状態:  Get-ScheduledTask -TaskName $TaskName | Get-ScheduledTaskInfo"
Write-Host "   停止:  Stop-ScheduledTask -TaskName $TaskName"
